folders:
  - ./:
      struct:
        - github/workflows/pre-commit
        - github/workflows/release-drafter
        - terraform/apps/environments
        - terraform/apps/aws-accounts
        - terraform/apps/init
